version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasksdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tasksdb?schema=public
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    command: sh -c "npx prisma migrate deploy --preview-feature || true; npm run dev"

volumes:
  db-data:
